accountapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'accountapp'

urlpatterns = [
    path('signup', views.signup_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('find', views.find_view, name='find')

]

buketlist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_summernote import urls as summernote_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accountapp.urls')),
    path('main/', include('main.urls')),
    path('editor/', include('django_summernote.urls')),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.main_view, name='main'),
    path('list', views.list_view, name='list'),
    path('mypage', views.mypage_view, name='mypage'),
    path('logout', views.logout_view, name='logout'),
    path('detail/<int:board_id>/', views.detail_view, name='detail')

]

accountapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    name = models.CharField(max_length=10)

main/models.py
from django.db import models

# Create your models here.

class Board(models.Model):
    board_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=20,null=True)
    content = models.TextField()
    writer = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'board'
        verbose_name = '게시판'
        verbose_name_plural = '게시판'

accountapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout

from .models import User

from django.conf import settings
from django.core.mail import EmailMessage
from django.contrib import messages

from django.template.loader import render_to_string
# Create your views here.


def login_view(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            print("로그인 성공")
            login(request, user)
            request.session['user_authenticated'] = True
            return redirect('mainapp:main')
        else:
            print("로그인 실패")
    return render(request, 'login.html')

def signup_view(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        re_password = request.POST.get('re_password')
        email = request.POST.get('email')

        if User.objects.filter(username=username).exists():
            messages.warning(request, "이미 사용 중인 아이디입니다.")
            return render(request, 'signup.html')
        elif password != re_password:
            messages.warning(request, "비밀번호가 일치하지 않습니다.")
            return render(request, 'signup.html')

        user = User.objects.create_user(username, email, password)
        user.save()
        return redirect('accountapp:login')
    return render(request, 'signup.html')

def find_view(request):
    context = {}
    if request.method == "POST":
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            if user is not None:
                context = {'name':user.name, 'username': user.username}
                template = render_to_string('email_templates.html', context)
                method_email = EmailMessage(
                    template,
                    settings.EMAIL_HOST_USER,
                    [email],
                )
                method_email.send(fail_silently=False)
                return render(request, 'send_id.html', context)
        except:
            messages.info(request, '저장된 아이디 없음')
    return render(request, 'find.html', context)

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout

from .models import Board
from .form import PostForm

# Create your views here.

def main_view(request):
    user_authenticated = request.session.get('user_authenticated', False)
    boards = Board.objects.all()
    if user_authenticated:
        print("로그인")
    else:
        print("로그아웃")
    return render(request, 'main.html', {'boards': boards})

def logout_view(request):
    logout(request)
    request.session['user_authenticated'] = False
    return redirect('mainapp:main')


def list_view(request):
    login_session = request.session.get('login_session','')
    context = {'login_session':login_session}

    if request.method == "GET":
        postForm = PostForm()
        context['forms'] = postForm
        return render(request, 'list.html', context)

    elif request.method == "POST":
        postForm = PostForm(request.POST)

        if postForm.is_valid():
            writer = User.objects.get(username=login_session)
            board = Board(
                title=postForm.cleaned_data['title'],
                content=postForm.cleaned_data['content'],
                writer=writer,
            )
            board.save()
            return redirect('mainapp:main')
        else:
            if postForm.errors:
                for value in postForm.errors.values():
                    context['error'] = value
            return render(request, 'list.html')

def mypage_view(request):
    return render(request, 'mypage.html')

def detail_view(request, board_id):
    board = get_object_or_404(Board, board_id=board_id)
    return render(request, 'detail.html', {'board': board})

accountapp/templates/find.html
<form method="POST">
    {% csrf_token %}
    이름 : <input type="text" name="name">
    이메일 : <input type="email" name="email">
    <input type="submit" name="email_submit">

    {% for message in messages %}
        {{ message }}
    {% endfor %}
</form>

accountapp/templates/login.html
<div style = "text-align:center">
    <form method = 'POST'>
        {% csrf_token %}
            <p>아이디</p><input name="username" type="text">
            <p>비밀번호</p><input name="password" type="password">
            <p></p><input type="submit" value="로그인">
    </form>

    {% if user.is_authenticated %}
        <a href ="{% url 'mainapp:logout' %}">로그아웃</a>

    {% else %}
        <a href = {% url 'accountapp:signup' %}>회원가입</a>
        <a href = {% url 'accountapp:find' %}>아이디를 잊으셨나요?</a>
    {% endif %}
</div>

accountapp/templates/send_id.html
아이디는 {{ username }} 입니다.
<a href="{% url 'accountapp:login' %}">로그인하러 가기</a>

accountapp/templates/signup.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

<form method = 'POST'>
    {% csrf_token %}
    <div style = "text-align:center">
        <p>이름</p><input name="name" type="text">
        <p>이메일</p><input name="email" type="text">
        <p>ID</p><input name="username" type="text">
        <p>PW</p><input name="password" type="password">
        <p>PW 확인</p><input name="re_password" type="password">
        <p></p><input type="submit" value="회원가입">
    </div>
</form>

main/templates/detail.html
{{ board.title }}
{{ board.writer }}
{{ board.content }}

main/templates/list.html
리스트 쓰기

<form action="" method="POST">
    {% csrf_token %}
    <div>
        <label for="{{ forms.title.id_for_label }}">{{ forms.title.label }}</label>
        {{ forms.title }}
    </div>
    <div>
        <label for="{{ forms.content.id_for_label }}">{{ forms.content.label }}</label>
        {{ forms.content }}
    </div>
    {% if error %}
        {{ error }}
    {% endif %}
    <button type="submit">제출</button>
</form>

main/templates/main.html
{% if user.is_authenticated %}
    <div div style = "text-align:right">
        {{ user.username }}님, 반갑습니다
        <a href = "{% url 'mainapp:list' %}">버킷리스트 작성하기</a>
        <a href = "{% url 'mainapp:mypage' %}">마이페이지</a>
        <a href ="{% url 'mainapp:logout' %}">로그아웃</a>
    </div>
    {% if boards %}
        <table>
            <thead>
                <tr>
                    <th>아이디</th>
                    <th>제목</th>
                </tr>
            </thead>
            <tbody>
                {% for board in boards %}
                    <tr>
                        <td>{{ board.writer }}</td>
                        <td><a href="{% url 'mainapp:detail' board.board_id %}">{{ board.title }}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>작성된 게시글이 없습니다.</p>
    {% endif %}
{% else %}
    <div div style = "text-align:right">
        <a href = "{% url 'accountapp:login' %}">로그인</a>
    </div>
    <div div style = "text-align:center">
        <p>로그인 후 게시판을 이용할 수 있습니다.</p>
    </div>
{% endif %}

main/templates/mypage.html
마이페이지